on join:
  send "&fWitaj &6%player% &fna serwerze!" to player
  if {first_join::%player's uuid%} is not set:
    set {first_join::%player's uuid%} to false
    send "&fZdobywaj &6butelki kaucyjne &fkopiac, atakujac i lowiac!" to player

on mine:  
  set {_lore1} to "&6Butelka, którą można zamienić w butelkomacie."
  set {_lore2} to "&fKliknij &8Shift + PPM &ftrzymając butelkę, by ją wymienić."
  set {_kaucyjna} to glass bottle named "&f&lButelka kaucyjna" with lore {_lore1} and {_lore2}
  
  if event-block is coal ore or deepslate coal ore:
    if chance of 20%:
      send "&fTen &8węgiel &fmiał w sobie butelki kaucyjne!" to player
      drop 1 of {_kaucyjna} at event-block
    else:
      send "&fNiestety, ten &8węgiel &fnie miał w sobie butelki kaucyjnej :(" to player

  else if event-block is copper ore or deepslate copper ore:
    if chance of 15%:
      send "&fTa &3miedź &fmiała w sobie butelkę kaucyjną!" to player
      drop 1 of {_kaucyjna} at event-block
    else:
      send "&fNiestety, ta &3miedź &fnie miała w sobie butelki kaucyjnej." to player

  else if event-block is iron ore or deepslate iron ore:
    if chance of 30%:
      send "&fTo &7żelażo &fmiało w sobie butelkę kaucyjną!" to player
      drop 1 of {_kaucyjna} at event-block
    else:
      send "&fTo &7żelażo &fnie miało w sobie butelki kaucyjnej!" to player

  else if event-block is gold ore or deepslate gold ore:
    if chance of 35%:
      send "&fTo &6złoto &fmiało w sobie butelkę kaucyjną! :)" to player
      drop 1 of {_kaucyjna} at event-block
    else:
      send "&fTo &6złoto &fnie miało w sobie butelki kaucyjnej!" to player

  else if event-block is emerald ore or deepslate emerald ore:
    if chance of 60%:
      send "&fTen &aemerald &fmiał w sobie butelkę kaucyjną!" to player
      drop 1 of {_kaucyjna} at event-block
    else:
      send "&fTen &aemerald &fnie miał w sobie butelki kaucyjnej." to player

  else if event-block is diamond ore or deepslate diamond ore:
    if chance of 65%:
      send "&fTen &bdiament &fmiał w sobie butelkę kaucyjną!!!" to player
      drop 1 of {_kaucyjna} at event-block
    else:
      send "&fTen &bdiament &fnie miał w sobie butelki kaucyjnej!" to player

  else if event-block is ancient debris:
    if chance of 70%:
      send "&fTen &8netheryt &fmiał w sobie butelkę kaucyjną!" to player
      drop 1 of {_kaucyjna} at event-block
    else:
      send "&fTen &8netheryt &fnie miał w sobie butelki kaucyjnej." to player

on death:
  set {_lore1} to "&6Butelka, którą można zamienić w butelkomacie."
  set {_lore2} to "&fKliknij &8Shift + PPM &ftrzymając butelkę, by ją wymienić."
  set {_kaucyjna} to glass bottle named "&f&lButelka kaucyjna" with lore {_lore1} and {_lore2}
  set {_niekaucyjna} to glass bottle named "&fButelka niekaucyjna" with lore "&6Bezużyteczny plastik."
  # ^^^ musze bo nie wiem jak robic globalne bez zapisywania na dysku xd

  if victim is not player:
    if attacker is player:
      if victim is a zombie:
        if chance of 30%:
          if chance of 90%:
            send "&fTen &2zombie &fmiał przy sobie butelkę kaucyjną!" to attacker
            drop 1 of {_kaucyjna} at victim
          else:
            send "&fTen &2zombie &fmiał butelkę ale &6niekaucyjną&f!! :(" to attacker
            drop 1 of {_niekaucyjna} at victim
        else:
          send "&fTen &2zombie &fnie miał przy sobie butelki kaucyjnej." to attacker
     
      else if victim is a skeleton:
        if chance of 35%:
          if chance of 90%:
            send "&fTen &7szkielet &fmiał przy sobie butelkę kaucyjną!" to attacker
            drop 1 of {_kaucyjna} at victim
          else:
            send "&fTen &7szkielet &fmiał przy sobie butelkę &6niekaucyjną&f!" to attacker
            drop 1 of {_niekaucyjna} at victim
        else:
          send "&fTen &7szkielet &fnie miał przy sobie butelki kaucyjnej!" to attacker

      else if victim is a creeper:
        if chance of 50%:
          if chance of 90%:
            send "&fTen &acreeper &fmiał przy sobię butelkę kaucyjną!" to attacker
            drop 1 of {_kaucyjna} at victim
          else:
            send "&fTen &acreeper &fmiał przy sobie butelkę &6niekaucyjną&f! :(" to attacker
            drop 1 of {_niekaucyjna} at victim
        else:
          send "&fTen &acreeper &fnie miał przy sobie butelki kaucyjnej! :(" to attacker

on rightclick:
  set {_lore1} to "&6Butelka, którą można zamienić w butelkomacie."
  set {_lore2} to "&fKliknij &8Shift + PPM &ftrzymając butelkę, by ją wymienić."
  set {_kaucyjna} to glass bottle named "&f&lButelka kaucyjna" with lore {_lore1} and {_lore2}
  set {_niekaucyjna} to glass bottle named "&fButelka niekaucyjna" with lore "&6Bezużyteczny plastik."

  if player is sneaking:
    if player's held item is glass bottle:
      if name of player's held item is "&f&lButelka kaucyjna":
        if line 1 of lore of player's held item is {_lore1}:
          set {_ilosc} to item amount of player's held item
          set {_piniadz} to {_ilosc} * 0.50
            
          set player's held item to air
          add {_piniadz} to player's money
          send "&fWymieniłeś &6%{_ilosc}% &fbutelek kaucyjnych na &6%{_piniadz}% &fzł!" to player
        
      else if name of player's held item is "&fButelka niekaucyjna":
        if line 1 of lore of player's held item is "&6Bezużyteczny plastik.":
          send "&cTo nie jest butelka kaucyjna! (to jest niekaucyjna)" to player

on fishing state change:
  set {_lore1} to "&6Butelka, którą można zamienić w butelkomacie."
  set {_lore2} to "&fKliknij &8Shift + PPM &ftrzymając butelkę, by ją wymienić."
  set {_kaucyjna} to glass bottle named "&f&lButelka kaucyjna" with lore {_lore1} and {_lore2}

  if event-fishing state is fish caught:
    if chance of 75%:
      set {_ile} to a random integer between 3 and 8
      send "&fWyłowiłeś &6%{_ile}% &fbutelek kaucyjnych!" to player
      drop {_ile} of {_kaucyjna} at player
    else:
      send "&fNie wyłowiłeś butelki kaucyjnej! :(" to player
